services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saferoute-be
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION:-1h}

      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}

    restart: unless-stopped