spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # EC2 실배포 시점엔 validate로 바꾸기
    properties:
      hibernate:
        format_sql: false

aws:
  region: ${AWS_REGION:us-east-2}
  s3:
    bucket: ${S3_BUCKET:project10-87-ohio-s3}
    presigned-url-expiration: 1m