spring:
  application:
    name: SafeRoute

  profiles:
    default: local

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

jwt:
  secret: ${JWT_SECRET}
  issuer: saferoute
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1h}

aws:
  region: ${AWS_REGION:us-east-2}
  s3:
    bucket: ${S3_BUCKET:project10-87-ohio-s3}
    presigned-url-expiration: 1m